schema_version: '2.0'
package: ethiopia2022-sars-cov2-extended-seir
version: 1.0.0
title: 'Model-based prediction of SARS-CoV-2 in Ethiopia: Extended SEIR model Lab'
description: 'Single-model lab wrapper for Model-based prediction of SARS-CoV-2 in
  Ethiopia: Extended SEIR model. One of three models used to describe dynamics of
  COVID-19 spread in Ethiopia. Here the two investigated population groups healthcare
  workers and community members are modeled as separate but interacti.'
models:
- alias: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model
  path: models/core
  parameters:
    model_path: data/MODEL2212310001.sbml
    integration_step: 0.1
- alias: visualisation
  path: models/visualisation
wiring:
- from: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.state
  to:
  - visualisation.epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model_state
- from: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.summary
  to:
  - visualisation.epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model_summary
- from: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.species_labels
  to:
  - visualisation.epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model_species_labels
io:
  inputs:
  - name: community_transmission_rate
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.community_transmission_rate
    label: Community Transmission Rate
  - name: incubation_period
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.incubation_period
    label: Incubation Period
  - name: recovery_period
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.recovery_period
    label: Recovery Period
  - name: initial_infected
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.initial_infected
    label: Initial Infected
  outputs:
  - name: state
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.state
    label: Model state
  - name: summary
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.summary
    label: Simulation summary
  - name: species_labels
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.species_labels
    label: Species labels
  - name: susceptible_community
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.susceptible_community
    label: Susceptible community
  - name: exposed_community
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.exposed_community
    label: Exposed community
  - name: infected_community
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.infected_community
    label: Infected community
  - name: recovered_community
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.recovered_community
    label: Recovered community
  - name: susceptible_healthcare_workers
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.susceptible_healthcare_workers
    label: Susceptible healthcare workers
  - name: exposed_healthcare_workers
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.exposed_healthcare_workers
    label: Exposed healthcare workers
  - name: infected_healthcare_workers
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.infected_healthcare_workers
    label: Infected healthcare workers
  - name: recovered_healthcare_workers
    maps_to: epidemiology_sbml_model_based_prediction_of_sars_cov_2_in_ethiopia_model2212310001_model.recovered_healthcare_workers
    label: Recovered healthcare workers
runtime:
  duration: 10.0
  communication_step: 0.1
  initial_inputs: {}
