schema_version: '2.0'
title: Liu2017 - Dynamics of Avian Influenza with Allee Growth Effect Lab
description: Single-model lab wrapper for Liu2017 - Dynamics of Avian Influenza with
  Allee Growth Effect. Sanhong Liu, Shigui Ruan & Xinan Zhang. It can be used to explore
  transmission dynamics and compare scenario outcomes across conditions.
models:
- alias: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model
  path: models/core
  parameters:
    model_path: data/BIOMD0000000709.xml
    integration_step: 0.1
- alias: visualisation
  path: models/visualisation
wiring:
- from: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.state
  to:
  - visualisation.epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model_state
- from: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.summary
  to:
  - visualisation.epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model_summary
- from: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.species_labels
  to:
  - visualisation.epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model_species_labels
io:
  inputs:
  - name: recovery_rate
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.recovery_rate
    label: Recovery Rate
  outputs:
  - name: state
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.state
    label: Model state
  - name: summary
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.summary
    label: Simulation summary
  - name: species_labels
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.species_labels
    label: Species labels
  - name: infected_avian_i_a
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.infected_avian_i_a
    label: Infected Avian (I a)
  - name: susceptible_avian_s_a
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.susceptible_avian_s_a
    label: Susceptible Avian (S a)
  - name: infected_human_i_h
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.infected_human_i_h
    label: Infected Human (I h)
  - name: susceptible_human_s_h
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.susceptible_human_s_h
    label: Susceptible Human (S h)
  - name: recovered_human_r_h
    maps_to: epidemiology_sbml_liu2017_dynamics_of_avian_influenza_with_allee_g_biomd0000000709_model.recovered_human_r_h
    label: Recovered Human (R h)
runtime:
  duration: 10.0
  communication_step: 0.1
  initial_inputs: {}
